api_version = "2025-07"

[[extensions]]
type = "function"
name = "Bundle Discount"
handle = "bundle-function"
runtime = "javascript"
uid = "0dd56d2d-8d75-b88e-1275-9ab6fee242190c11755b"

  [[extensions.targeting]]
  module = "./src/run.js"
  target = "purchase.product-discount.run"